// constantes para os tokens 
enum Tag { ID = 256, INTEGER, FLOATING, STRING, TYPE, TRUE, FALSE, MAIN, IF, THEN, ELSE, NUM, 
            WHILE, DO, OR, AND, EQ, ATT, NEQ, LTE, GTE, LT, LE, NE, GT,
            BOOLEAN,  LBRACE, RBRACE, LPAREN, RPAREN, LBRACKET, RBRACKET, SEMICOLON,
            SIGN_PLUS, SIGN_MINUS, SIGN_MULT, SIGN_DIV, EXCLAMATION};